# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

splinePath <- function(x, y, degree, knots, detail) {
    .Call('hierarchicalSets_splinePath', PACKAGE = 'hierarchicalSets', x, y, degree, knots, detail)
}

getSplines <- function(x, y, id, detail) {
    .Call('hierarchicalSets_getSplines', PACKAGE = 'hierarchicalSets', x, y, id, detail)
}

setClustering <- function(P, I, setNames, threshold) {
    .Call('hierarchicalSets_setClustering', PACKAGE = 'hierarchicalSets', P, I, setNames, threshold)
}

pairSummary <- function(P, I, order) {
    .Call('hierarchicalSets_pairSummary', PACKAGE = 'hierarchicalSets', P, I, order)
}

getOutliers <- function(clusters, P, I, count) {
    .Call('hierarchicalSets_getOutliers', PACKAGE = 'hierarchicalSets', clusters, P, I, count)
}

